[project]
name = "python"
version = "1.0.3"
description = "My portfolio website"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "frozen-flask>=1.0.2",
    "mypy>=1.19.0",
    "ruff>=0.14.10",
    "ty>=0.0.8",
]

[tool.ruff]
indent-width = 4
line-length = 79

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = ["I"]
