[project]
name = "resumake"
version = "1.1"
description = "My portfolio website compiler utilizing Jinja, Python, and make"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
render_template = "build:render_template"
render_cv = "build:render_cv"

[dependency-groups]
dev = [
    "jinja2>=3.1.6",
    "minify-html>=0.18.1",
    "pyyaml>=6.0.3",
    "ruff>=0.14.10",
    "types-pyyaml>=6.0.12.20260906",
]

[tool.uv]
package = true

[tool.ruff]
indent-width = 4
line-length = 79

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = ["I"]
