[project]
name = "resumake"
version = "3.0"
description = "My portfolio website compiler utilizing Python, Jinja, and Make"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.1.6",
    "minify-html>=0.18.1",
    "pyyaml>=6.0.3",
]

[project.scripts]
build_page = "build:build_page"
build_cv = "build:build_cv"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.14.10",
    "types-pyyaml>=6.0.12.20260906",
]

[tool.uv]
package = true

[tool.ruff]
indent-width = 4
line-length = 79

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = ["I"]
